# Generated by Django 5.2.13 on 2026-05-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default=2, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
