# Generated by Django 5.2.13 on 2026-05-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
