# Generated by Django 5.2.13 on 2026-05-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_seller_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seller_note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='default', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
